### ISSUE TITLE
Burst Tire clips into the rim

### ISSUE THREAD

**Issue by of-ravens-claw** [bttfv/BackToTheFutureV#25]
## The Problem
Screenshot:

Front: ![Problem in the Front Wheel](https://cdn.discordapp.com/attachments/498209637150097408/944765805957103646/unknown.png)
Rear: ![Problem in the Rear Wheel](https://cdn.discordapp.com/attachments/498209637150097408/944765829877211136/unknown.png)
The Lines in `vehicles.meta` responsible:
```
			<wheelScale value="0.197500"/>
			<wheelScaleRear value="0.197500"/>
```
## The Fix
Change the responsible lines to the following:
```
			<wheelScale value="0.202500"/>
			<wheelScaleRear value="0.230500"/>
```
Screenshot:
Front: ![Fixed Front](https://cdn.discordapp.com/attachments/498209637150097408/944780946979315793/unknown.png)
Rear: ![Fixed Rear](https://cdn.discordapp.com/attachments/498209637150097408/944781083826860083/unknown.png)

Also works with the White Walls ![](https://cdn.discordapp.com/attachments/498209637150097408/944781593531281429/unknown.png)

**Comment by nomakewan** [comment]
These fixes were included as part of the merged pull request. Thank you very much for your assistance!
